import { Ticket } from "@/types/ticket";

export const mockTickets: Ticket[] = [
  {
    id: '1',
    title: 'Login issue with dashboard',
    description: 'User cannot access the dashboard after successful login',
    status: 'new',
    priority: 'high',
    customer: 'John Doe',
    email: 'john@example.com',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    title: 'Payment gateway failure',
    description: 'Payments are not processing through the payment gateway',
    status: 'new',
    priority: 'high',
    customer: 'Jane Smith',
    email: 'jane@example.com',
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-14'),
  },
  {
    id: '3',
    title: 'Dark mode implementation',
    description: 'Implement dark mode across all application pages',
    status: 'ongoing',
    priority: 'medium',
    customer: 'Bob Johnson',
    email: 'bob@example.com',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-13'),
    assignedTo: 'Support Agent 1',
  },
  {
    id: '4',
    title: 'Mobile responsiveness issues',
    description: 'UI breaks on mobile devices for ticket details page',
    status: 'ongoing',
    priority: 'medium',
    customer: 'Alice Brown',
    email: 'alice@example.com',
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-14'),
    assignedTo: 'Support Agent 2',
  },
  {
    id: '5',
    title: 'Account deletion request',
    description: 'Customer wants to delete their account and all data',
    status: 'closed',
    priority: 'low',
    customer: 'Charlie Wilson',
    email: 'charlie@example.com',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-08'),
    assignedTo: 'Support Agent 1',
  },
  {
    id: '6',
    title: 'API integration support',
    description: 'Help needed with third-party API integration',
    status: 'closed',
    priority: 'medium',
    customer: 'Diana Lee',
    email: 'diana@example.com',
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-07'),
    assignedTo: 'Support Agent 3',
  },
  {
    id: '7',
    title: 'Email notification problem',
    description: 'Users not receiving email notifications',
    status: 'new',
    priority: 'medium',
    customer: 'Michael Chen',
    email: 'michael@example.com',
    createdAt: new Date('2024-01-13'),
    updatedAt: new Date('2024-01-13'),
  },
  {
    id: '8',
    title: 'Database connection timeout',
    description: 'Database connections timing out under heavy load',
    status: 'ongoing',
    priority: 'high',
    customer: 'Sarah Williams',
    email: 'sarah@example.com',
    createdAt: new Date('2024-01-11'),
    updatedAt: new Date('2024-01-14'),
    assignedTo: 'Support Agent 2',
  },
  {
    id: '9',
    title: 'Feature request: Export to PDF',
    description: 'Add ability to export tickets as PDF reports',
    status: 'new',
    priority: 'low',
    customer: 'Robert Taylor',
    email: 'robert@example.com',
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    id: '10',
    title: 'Password reset not working',
    description: 'Password reset functionality returns error',
    status: 'ongoing',
    priority: 'high',
    customer: 'Lisa Anderson',
    email: 'lisa@example.com',
    createdAt: new Date('2024-01-09'),
    updatedAt: new Date('2024-01-14'),
    assignedTo: 'Support Agent 1',
  },
  {
    id: '11',
    title: 'UI alignment issues',
    description: 'Text and buttons misaligned in customer portal',
    status: 'closed',
    priority: 'low',
    customer: 'David Martinez',
    email: 'david@example.com',
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date('2024-01-06'),
    assignedTo: 'Support Agent 3',
  },
  {
    id: '12',
    title: 'Performance optimization',
    description: 'Slow loading times on ticket list page',
    status: 'closed',
    priority: 'medium',
    customer: 'Jennifer Lopez',
    email: 'jennifer@example.com',
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date('2024-01-05'),
    assignedTo: 'Support Agent 2',
  },
];